module.exports = {
	ORIGIN_IMAGE_FOLDER : 'origin-images',

	SMALL_IMAGE_FOLDER : 'small-images',
	SMALL_IMAGE_WIDTH : 200,
	SMALL_IMAGE_HEIGHT : 200,

	MEDIUM_IMAGE_FOLDER : 'medium-images',
	MEDIUM_IMAGE_WIDTH : 400,
	MEDIUM_IMAGE_HEIGHT : 400,

	NUMBER_OF_IMAGES_RESIZED_SIMULTANEOUSLY : 10,
	NUMBER_OF_IMAGES_UPLOADED_SIMULTANEOUSLY : 10,

	ACCESS_KEY_ID : '[ACCESS_KEY_ID]',
	SECRET_ACCESS_KEY :'[SECRET_ACCESS_KEY]', 
	PRIVATE_BUCKET : '[PRIVATE_BUCKET]',
	PUBLIC_BUCKET : '[PUBLIC_BUCKET]',
	REGION : 'ap-southeast-1',

	AWS_CLOUDFRONT_ACCCESS_KEY_ID: '[AWS_CLOUDFRONT_ACCCESS_KEY_ID]',
	PATH_TO_AWS_CLOUDFRONT_PRIVATE_KEY: '[PATH_TO_AWS_CLOUDFRONT_PRIVATE_KEY]',
	EXPIRE_TIME: 30000, // in miliseconds 
	DOMAIN_NAME: '[DOMAIN_NAME_YOUR_CLOUDFRONT]', 
}