module.exports = {
	ORIGIN_IMAGE_FOLDER : 'origin-images',

	SMALL_IMAGE_FOLDER : 'small-images',
	SMALL_IMAGE_WIDTH : 200,
	SMALL_IMAGE_HEIGHT : 200,

	MEDIUM_IMAGE_FOLDER : 'medium-images',
	MEDIUM_IMAGE_WIDTH : 400,
	MEDIUM_IMAGE_HEIGHT : 400,

	NUMBER_OF_IMAGES_RESIZED_SIMULTANEOUSLY : 10,
	NUMBER_OF_IMAGES_UPLOADED_SIMULTANEOUSLY : 10,

	ACCESS_KEY_ID : 'AKIAIS4LMP3FBCC7ZHDA',
	SECRET_ACCESS_KEY :'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', 
	PRIVATE_BUCKET : 'raydar-private-image',
	PUBLIC_BUCKET : 'raydar-public-image',
	REGION : 'ap-southeast-1',

	AWS_CLOUDFRONT_ACCCESS_KEY_ID: 'APKAJ4GCQSDEGBXMMQYQ',
	PATH_TO_AWS_CLOUDFRONT_PRIVATE_KEY: './cloudfrontprivatekey/pk-APKAJ4GCQSDEGBXMMQYQ.pem',
	EXPIRE_TIME: 30000, // in miliseconds 
	DOMAIN_NAME: 'https://d1zfw5v74lamk1.cloudfront.net', 
}